Browser UI for browsing area maps in database
lotheac/bcproxy pull request #3
Opened 2020-08-30 20:41 UTC by rhietala

2020-08-31 09:13 UTC, lotheac requested changes
So, some general feedback here:

area_to_json.py is quite slow, which is why my initial PoCs pregenerated the json for sigma to be consumed; you've essentially copied that logic here, which makes page loads slow, but that is fine for now and is a good start.

On a higher architectural level, the splitting into subgraphs  and their respective positioning should be controllable by the end user (since it's quite difficult to lay out an arbitrarily complicated map programmatically). So this PoC is fine, but we need to eventually extend the db format to store information about at least which subgraph each node belongs to, and the positioning of the subgraphs, and room notes. Maybe also individual node positioning if necessary.

So if we can store some of the layout/positioning data in the db, then the common case for page loads should be fast -- we would only need to run the expensive/horribly-ugly logic for initial positioning if there are some nodes in the graph that don't have subgraph/positioning data.

Other than that just some nitpicks about newlines.

2020-08-31 09:13 UTC, lotheac commented on mapbrowser/templates/base.html
> +</html>
add newline

2020-08-31 09:13 UTC, lotheac commented on mapbrowser/templates/map.html
> +{% endblock %}
add newline

2020-08-31 09:13 UTC, lotheac commented on mapbrowser/.gitignore
> +__pycache__/
add newline

2020-10-08 19:54 UTC, rhietala commented
Instead of merging the mapbrowser web app here, let's continue development in its own repo https://github.com/bat-boys/bcproxy-mapbrowser/

2020-10-08 19:54 UTC, closed without merging